### PR TITLE
Support miniflare's storage option when on local mode

### PR DESCRIPTION
**Pull request by bardouni**
Nothing fancy here, I have just made wrangler pass the option to miniflare.

### CODE REVIEW

**Comment by bardouni** [comment]
And excuse my Naming skills :)

**Comment by threepointone** [comment]
Could you explain how and why you use redis for storage with local mode? Why not use regular cloudflare kv/do namespaces? Any details would be helpful to understand this feature request.

**Comment by bardouni** [comment]
Because I'm using the cache api in local mode which uses miniflare behind the scene.
And I need a way to invalidate this cache, I mock the invalidation script ( in development ) to invalidate from redis instead of cache-purge from api.cloudflare.com.
At https://www.lightfunnels.com, We have a page builder that stores pages as json and render it using workers.
We tried both.
Do had sotrage limit issue.
KV has invalidation delay issue where users would wait up to one minute for the invalidation.
So we ended up with using the cache api.

**Comment by threepointone** [comment]
But in local mode, is there a reason you use redis instead of just the file system? Could you modify the script to delete the folder instead? 

(Also of interest to you, would be that we're going to be shipping improvements to cache clearing https://blog.cloudflare.com/part1-coreless-purge/)

**Comment by bardouni** [comment]
That could work too actually

**Comment by bardouni** [comment]
And yes, I read that post few days ago, Can't wait to see it in action. Thank you again :D

**Comment by threepointone** [comment]
I think we should consider the redis thing to be separate. I want to push back on that a little because we're trying not to have any network deps for local mode. Happy to consider the other change. Here are my suggestions - 

- remove the bits about redis  
- using `--experimental-enable-local-persistence` should log a warning to use `--experimental-local-persistence` instead 
- `--experimental-local-persistence-path` should be a string input, that's used as the path to store the files (which, as it is, currently defaults to the temp dir we use for built workers)
How does that sound?

**Comment by bardouni** [comment]
Yeah looks fine, I can work on this
W'll PR something soon

**Comment by bardouni** [comment]
Hi @threepointone 
What do you think of this ?
image

**Comment by threepointone** [comment]
A solution here is to strip out `/` from keys

**Pull request closed without merging**
