### PR TITLE
Added transferred_classes to migrations config

### LINKED ISSUE #2305: 🐛 BUG: Incorrect warning about Durable Object transfer migrations
### What version of `Wrangler` are you using?

2.4.4

### What operating system are you using?

Mac

### Describe the Bug

Wrangler warns when a Durable Object transfer migration is specified in wrangler.toml.

For example, if this is present in wrangler.toml for `test-worker-b`:

```
[[migrations]]
tag = "v1"
transferred_classes = [{from_script = "test-worker-a", from="DurableObjectA", to = "DurableObjectA" }]
```

Then on publish, `DurableObjectA` will be successfully transferred from `test-worker-a` to `test-worker-b`. However, wrangler displays the following warning during the publish operation:

```
 ⛅️ wrangler 2.4.4 
-------------------
▲ [WARNING] Processing wrangler.toml configuration:

    - Unexpected fields found in migrations field: "transferred_classes"
```

Can I please also recommend that the [documentation](https://developers.cloudflare.com/workers/learning/using-durable-objects/#configuring-durable-object-classes-with-migrations) be updated to include the transferred_classes syntax. I had to figure it out by looking at the wrangler v1 sources.

### PR DESCRIPTION
**Pull request by geelen**
Fixes #2305

### CODE REVIEW

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
Thanks @geelen - could you add validation tests to packages/wrangler/src/__tests__/configuration.test.ts

Could you also add some JSDoc document comments to the new properties `from`, `from_script` and `to`? I couldn't quite work out what each field meant from looking at the code here.

I assume that there will be a Cloudflare docs update to go with this?

**Comment by rozenmd** [comment]
Looks like this issue closes https://github.com/cloudflare/wrangler2/issues/2305 ?

**Comment by petebacondarwin** [comment]
Do you want to clean this up and get it landed @geelen ?

**Comment by lrapoport-cf** [comment]
hi @geelen :)  do you still plan to loop back to this PR? if not, we'll plan to close it

**Comment by rozenmd** [comment]
@lrapoport-cf: Glen's OOO until end of October at least, fyi

**Comment by lrapoport-cf** [comment]
hey @geelen :) i believe you're back in office now so wanted to check in on this -- do you still plan to loop back to this PR? if not, we'll plan to close it

**Pull request closed without merging**
