### PR TITLE
Redirect workers.new to the playground

### PR DESCRIPTION
**Pull request by penalosa**
Fixes # [insert GH or internal issue number(s)].

**What this PR solves / how to test:**
Redirect `workers.new` to the new Workers Playground

**Associated docs issue(s)/PR(s):**

- [insert associated docs issue(s)/PR(s)]

**Author has included the following, where applicable:**

- [ ] Tests
- [ ] Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))

**Reviewer is to perform the following, as applicable:**

- Checked for inclusion of relevant tests
- Checked for inclusion of a relevant changeset
- Checked for creation of associated docs updates
- Manually pulled down the changes and spot-tested

**Note for PR author:**

We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take inspiration and learn from it.

### CODE REVIEW

**Review by admah — APPROVED** [review]
LGTM!

**Comment by irvinebroque** [comment]
@penalosa @admah @lrapoport-cf  — @tsmith512 and I just realized that links to `workers.new/typescript` are still redirecting to Stackblitz, not to the Playground.

**Comment by penalosa** [comment]
@irvinebroque This was intentional so as not to break old links. We can definitely change that behaviour though?

**Comment by irvinebroque** [comment]
I see. Right now none of the examples on Stackblitz work, and in order to
get them to work, have to continue to use Wrangler V2.

My only opinion is that we should direct people to something that works.

**Comment by admah** [comment]
@irvinebroque do you know where these links are? Stackblitz doesn't work with wrangler v3+ and may not anytime soon. The other issue here is that our playground doesn't currently support TS, so redirecting users using this URL is also not the best option IMO.

**Comment by penalosa** [comment]
@admah they're defined within the `workers.new` package, I think. I wonder where they're actually used though—do we reference them on the docs or anything like that?

**Comment by admah** [comment]
@penalosa I don't see any mention of `/typescript` in the docs. It looks like all current docs links for `workers.new` are Stream related. Of note, traffic to `/typescript` is extremely limited. Maybe it's only internal use?

**Comment by lrapoport-cf** [comment]
to close the loop, is there any action requested here?

**Pull request merged**
