### PR TITLE
Allow CI deploying non-private packages

### PR DESCRIPTION
**Pull request by GregBrimble**
## What this PR solves / how to test

workers-shared is the only non-private and deployable package. And it was skipped in the last release because of this check.

## Author has addressed the following

- Tests
  - [ ] TODO (before merge)
  - [x] Included
  - [ ] Not necessary because: 
- E2E Tests CI Job required? (Use "e2e" label or ask maintainer to run separately)
  - [ ] I don't know
  - [ ] Required / Maybe required
  - [x] Not required because: no coverage
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [ ] TODO (before merge)
  - [ ] Included
  - [x] Not necessary because: internal tooling change
- Public documentation
  - [ ] TODO (before merge)
  - [ ] Cloudflare docs PR(s): 
  - [x] Not necessary because: internal tooling change

### CODE REVIEW

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
I'm not keen on this change. If someone adds a deploy script to an npm package changeset will attempt to deploy it twice.

What if we change the name of the script that triggers the non-npm deployment to something like `deployWorkers`?

**Comment by GregBrimble** [comment]
Happy to go with whatever devprod want here. If they want `deployWorkers`, that's easily changed :)

**Comment by petebacondarwin** [comment]
Actually, given we already have a workers-sdk section in packages (in order to trigger prerelease previews) (e.g. https://github.com/cloudflare/workers-sdk/blob/main/packages/miniflare/package.json#L106). How about we just add some config there they says when a package should be also deployed outside of the npm deployments?

**Comment by GregBrimble** [comment]
Yup, I like that. Can do!

**Review by petebacondarwin — APPROVED** [review]

**Pull request merged**
