### PR TITLE
Fix local registry being able to start only once in unstable_dev

### PR DESCRIPTION
**Pull request by kuba-orlik**
When using `unstable_dev`, it's not possible to start multiple workers in a sequence. Once you stop one worker, the local registry is closed and cannot be started again. This fixed that by clearing the `server` variable once the server is stopped

### CODE REVIEW

**Comment by rozenmd** [comment]
Thanks for the PR @kuba-orlik ! 

Do you mind rebasing onto main or merging main into this branch? I just fixed an issue with a test that'll fail for external contributors.

**Comment by kuba-orlik** [comment]
Rebase complete :)

**Comment by rozenmd** [comment]
by the way @kuba-orlik - any chance you could share a code sample of what you're trying to do?

**Comment by kuba-orlik** [comment]
Not necessarily a code sample, but the gist of it is that I'm writing e2e tests for a worker. I want to run it multiple times during the tests, to see how it behaves with various configs.

My tests were failing, because running `.stop()` on a worker irreversibly killed the local worker registry. Any worker started afterwards kept failing to register and polluting the stderr with error messages related to that fact

**Comment by rozenmd** [comment]
Ah okay, that makes sense, I forgot folks might want to turn a server on/off throughout a test 😅 

I'll try make a test case to reproduce the issue tomorrow

**Comment by rozenmd** [comment]
Actually @kuba-orlik can you post a minimal reproduction of the issue? I'm not able to see the same error with the following test in Jest:

```js
const { unstable_dev } = require("wrangler");

describe("Worker", () => {
  let worker;

  it("should return Hello World", async () => {
    worker = await unstable_dev(
      "src/index.js",
      {},
      { disableExperimentalWarning: true }
    );
    let resp = await worker.fetch();
    if (resp) {
      const text = await resp.text();
      expect(text).toMatchInlineSnapshot(`"Hello World!"`);
    }
    await worker.stop();

    worker = await unstable_dev(
      "src/index.js",
      {},
      { disableExperimentalWarning: true }
    );
    resp = await worker.fetch();
    if (resp) {
      const text = await resp.text();
      expect(text).toMatchInlineSnapshot(`"Hello World!"`);
    }
    await worker.stop();
  });
});
```

**Comment by kuba-orlik** [comment]
This is a kind-of minimal reproduction of the problem:

```js
const { unstable_dev } = require('wrangler')
const config = {
  config: '/tmp/wrangler-test.toml',
  bundle: false,
  logLevel: 'debug',
  forceLocal: true,
  localProtocol: 'http',
  port: 1337,
}

;(async function () {
  let worker = await unstable_dev('dist/worker.js', config, {
    disableExperimentalWarning: true,
  })
  await worker.stop()

  worker = await unstable_dev('dist/worker.js', config, {
    disableExperimentalWarning: true,
  })
  resp = await worker.fetch()
  await worker.stop()
})()
```

The code itself *works*, but after creating the second worker onwards it throws errors into stderr, like:

```
Failed to register worker in local service registry TypeError: fetch failed
    at Object.processResponse (/home/kuba/projects/cloudflare/zaraz-worker/node_modules/wrangler/wrangler-dist/cli.js:8846:27)
    at /home/kuba/projects/cloudflare/zaraz-worker/node_modules/wrangler/wrangler-dist/cli.js:9178:42
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: Error: connect ECONNREFUSED 127.0.0.1:6284
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 6284
  }
}
```

The errors don't break the flow of the tests, but they do pollute their output

**Comment by petebacondarwin** [comment]
Is this PR still relevant? I think there was some work on DevRegistry recently to change this behaviour?

**Comment by kuba-orlik** [comment]
It's still relevant. The error `Failed to register worker in local service registry TypeError: fetch failed` error message still appears when using 2.8.0

**Review by JacobMGEvans — APPROVED** [review]
I paired with you on this. It is a simple change with important fix.

**Pull request merged**
