### PR TITLE
[wrangler] fix: Use Windows SYSTEMROOT env var for finding netstat

### PR DESCRIPTION
**Pull request by ZakKemble**
**What this PR solves / how to test:**

Currently, the drive letter of os.homedir() (the user's home directory) is used to build the path to netstat.exe. However, user directories are not always on the same drive as the Windows installation, in which case the path to netstat will be incorrect. Now we use the %SYSTEMROOT% environment variable which correctly points to the installation path of Windows.

**Author has included the following, where applicable:**

- [ ] Tests
- [x] Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))

**Reviewer is to perform the following, as applicable:**

- Checked for inclusion of relevant tests
- Checked for inclusion of a relevant changeset
- Checked for creation of associated docs updates
- Manually pulled down the changes and spot-tested

### CODE REVIEW

**Comment by Skye-31** [comment]
I note at https://github.com/nodejs/node/blob/ad0bbaf34aa3150b4f3507b9973b6f5e8ed47474/lib/os.js#L186 that they fall back to `process.env.Windir` in the case that `process.env.SystemRoot isn't present - it might be a good idea to do so here also? 🙂
image

**Comment by ZakKemble** [comment]
Good point, though from what I can tell WinDir is from the Win9x days and SystemRoot is what everything should be using now. WinDir is just for compatibility reasons. I don't think we need 9x support anymore? Haha

**Comment by Skye-31** [comment]
Fair enough, I was unfamiliar with both of these, thought it might be wise to mention 😄

**Review by RamIdeas — APPROVED** [review]

**Comment by RamIdeas** [comment]
Hey @ZakKemble! Thank you very much for this PR and apologies for the delay responding. I would be happy to merge this once the tests pass

**Pull request merged**
