### PR TITLE
startDevWorker Milestone 1 - Reboot

### PR DESCRIPTION
**Pull request by RamIdeas**
This is the PR to reintroduce cloudflare/workers-sdk#3960 

TODO:
- [x] https://github.com/cloudflare/workers-sdk/issues/4168
- [ ] https://github.com/cloudflare/workerd/issues/1366
- [x] ~https://github.com/cloudflare/workers-sdk/issues/4167~
- [x] ~https://github.com/cloudflare/workers-sdk/issues/4166~
- [x] https://github.com/cloudflare/workers-sdk/issues/4165
- [ ] (TODO: create issue) bug: dev registry contains UserWorker address, not ProxyWorker

**What this PR solves / how to test:**

Please use the prerelease builds in the bot comment below to test: `wrangler dev`, `wrangler dev --remote`, `unstable_dev()` in local and remote mode, on your setup and post your issues in comments below

**Associated docs issue(s)/PR(s):**

- [insert associated docs issue(s)/PR(s)]

**Author has included the following, where applicable:**

- [ ] Tests
- [ ] Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))

**Reviewer is to perform the following, as applicable:**

- Checked for inclusion of relevant tests
- Checked for inclusion of a relevant changeset
- Checked for creation of associated docs updates
- Manually pulled down the changes and spot-tested

**Note for PR author:**

We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take inspiration and learn from it.

### CODE REVIEW

**Comment by RamIdeas** [comment]
> @RamIdeas would it be possible to separate out the individual bug fixes into separate PRs?

@penalosa the 2 commits to fix 2 of the bugs were quite tiny and encapsulated in individual commits. I think reviewing each commit will be easy enough

If there are bigger changes, I will absolutely open a separate PR 👍

**Comment by Cyb3r-Jak3** [comment]
I tested this in my [project](https://github.com/Cyb3r-Jak3/workers-serverless-api) and seeing warning released to `Your worker created multiple branches of a single stream...` with this version [workflow](https://github.com/Cyb3r-Jak3/workers-serverless-api/actions/runs/6592825491/job/17914196978) (in the test stage) whereas the latest wrangler dev didn't have those errors [workflow](https://github.com/Cyb3r-Jak3/workers-serverless-api/actions/runs/6592810127/job/17914149829). 

When testing locally on Windows 10 I also get the following additional messages to stderr
```
stderr | src/git.test.ts > Git Endpoints > Git Repos
workerd/jsg/util.c++:275: error: e = workerd/util/sqlite.c++:894: failed: SQLite failed; sqlite3_errmsg(db) = cannot commit transaction - SQL statements in progress;  sqlite3_step()
stack: 7ff60e46d2af 7ff60e802419 7ff60e8ada63 0; sentryErrorContext = jsgInternalError
workerd/jsg/util.c++:275: error: e = workerd/util/sqlite.c++:894: failed: SQLite failed; sqlite3_errmsg(db) = cannot commit transaction - SQL statements in progress;  sqlite3_step()
stack: 7ff60e46d2af 7ff60e802419 7ff60e8ada63 0; sentryErrorContext = jsgInternalError

stderr | src/git.test.ts > Git Endpoints > Git User
workerd/jsg/util.c++:275: error: e = kj/filesystem-disk-win32.c++:249: failed: DeleteFileW(path.begin()): #5 Access is denied.; dbgStr(path) = \\?\F:\git\workers\severless-api\.wrangler\state\v3\kv\a3030e4701ed406ba337ca8bd9108dda\blobs\3c82b7cd5bfbf427963c8519cc2107c742efd2080a295d5fee70ef81031353690000022f9a055c8c
stack: 7ff60e46d2af 7ff60e498d9a 7ff60e7748ef 0 0; sentryErrorContext = jsgInternalError
```

**Comment by jadbox** [comment]
Does this help with supporting `wranger pages dev --remove`?

**Comment by RamIdeas** [comment]
Hi @Cyb3r-Jak3! Thanks for your feedback and apologies for the delay. We used your test suite to analyse the stability of these changes. Github got a bit confused with this PR and so I closed this and opened a new PR https://github.com/cloudflare/workers-sdk/pull/4413 – could you try the prerelease build from there and let us know how it goes please?

**Comment by RamIdeas** [comment]
@jadbox although we are not focusing on pages dev directly, `wrangler pages dev` uses `unstable_dev` under-the-hood and therefore will benefit from the changes and stability improvements indirectly

**Pull request closed without merging**
