### PR TITLE
Disable warnings for invalid config in wrangler login & logout

### PR DESCRIPTION
**Pull request by WalshyDev**
## What this PR solves / how to test

Fixes [WO-184](https://jira.cfdata.org/browse/WO-184)

## Author has addressed the following

- Tests
  - [ ] TODO (before merge)
  - [x] Tests included
  - [ ] Tests not necessary because:
- E2E Tests CI Job required? (Use "e2e" label or ask maintainer to run separately)
  - [ ] I don't know
  - [ ] Required
  - [x] Not required because: no changes
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [ ] TODO (before merge)
  - [x] Changeset included
  - [ ] Changeset not necessary because:
- Public documentation
  - [ ] TODO (before merge)
  - [ ] Cloudflare docs PR(s): 
  - [x] Documentation not necessary because: no public changes

### CODE REVIEW

**Comment by penalosa** [comment]
I'm not sure I understand the intention here—in this case there is an invalid `wrangler.toml` file, and I think we do want to warn. It's not a hard error, so this shouldn't be causing user issues

**Comment by WalshyDev** [comment]
Yeah but warning on an invalid wrangler.toml during login/logout just doesn't make much sense - we read it just for the metrics value but we don't use anything else.

A user seeing a warning after logging in is confusing.

**Comment by threepointone** [comment]
Actually a good idea, I like it

**Review by penalosa — APPROVED** [review]

**Comment by penalosa** [comment]
For context, I had originally blocked this because I had thought that config being invalid could potentially cause weird behaviour in login, primarily around the `account_id` field. Having read the PR more closely, since we're only reading config _after_ actually logging in or out that concern is removed. Thanks @WalshyDev for this!

**Review by edmundhung — APPROVED** [review]

**Pull request merged**
