### PR TITLE
chore: update pnpm-lock.yaml

### PR DESCRIPTION
**Pull request by threepointone**
## What this PR solves / how to test

Runinning `pnpm i` results in a changed lockfile, looks like we forgot to commit it somewhere.  

Fixes #0000 (Just a chore)

## Author has addressed the following

- Tests
  - [ ] TODO (before merge)
  - [ ] Tests included
  - [x] Tests not necessary because: internal
- E2E Tests CI Job required? (Use "e2e" label or ask maintainer to run separately)
  - [ ] I don't know
  - [ ] Required
  - [x] Not required because: internal
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [ ] TODO (before merge)
  - [ ] Changeset included
  - [x] Changeset not necessary because: internal
- Public documentation
  - [ ] TODO (before merge)
  - [ ] Cloudflare docs PR(s): 
  - [x] Documentation not necessary because: internal

### CODE REVIEW

**Comment by threepointone** [comment]
friction log, this 
image


generated this 

image

**Comment by petebacondarwin** [comment]
This has come up a number of times. Every time we fix it the changesets Version Packages PR reverts it. 😢

**Review by penalosa — APPROVED** [review]

**Comment by threepointone** [comment]
Oh I can't merge it, could one of you please do so? thank you!

**Comment by petebacondarwin** [comment]
There is little point in merging this without fixing the changesets problem because it will re-appear after the next release later today.

**Comment by threepointone** [comment]
That's fine, I'll send a PR again after the release while we wanit for a proper fix. But I can't test PRs or send fresh PRs without this file popping up everytime.

**Pull request merged**
