### PR TITLE
Rename unstable_dev() to dev()

### LINKED ISSUE #1420: Promote unstable_dev() to dev()
This issue will track the issues required to promote `api/unstable_dev()` to `api/dev`

- We should rewrite our local-mode tests to use unstable_dev: 
  - https://github.com/cloudflare/wrangler2/issues/1419
  - this is blocked until we implement a react-free version of `unstable_dev`, as it doesn't currently work in CI:
    - https://github.com/cloudflare/wrangler2/pull/1538
- https://github.com/cloudflare/wrangler2/issues/1756
- The API needs to export its types for consumers, tracked by: 
  - https://github.com/cloudflare/wrangler2/issues/1387
- We need to finalise the types that `dev` uses for the options config: 
  - https://github.com/cloudflare/wrangler2/issues/1418
- Stabilize unstable_dev's options
  - https://github.com/cloudflare/wrangler2/issues/2344

### PR DESCRIPTION
**Pull request by rozenmd**
What this PR solves / how to test:

This PR resolves https://github.com/cloudflare/wrangler2/issues/1420

Associated docs issues/PR:

- TODO

Author has included the following, where applicable:

- [x] Tests
- [x] Changeset

Reviewer has performed the following, where applicable:

- [ ] Checked for inclusion of relevant tests
- [ ] Checked for inclusion of a relevant changeset
- [ ] Checked for creation of associated docs updates
- [ ] Manually pulled down the changes and spot-tested

Fixes #1420

### CODE REVIEW

**Comment by rozenmd** [comment]
We did it @threepointone 

We did it joe gif

**Comment by penalosa** [comment]
Just bringing up this point from the prior discussion:
> https://github.com/cloudflare/wrangler2/discussions/2315#discussioncomment-4284541
> I definitely vote we have like two properties stabilised (port and script, a path relative to where it's called), and mark everything else as experimental to give the most flexibility

From a quick read of this PR, it looks like there's an `experimental` property, but most things aren't part of it:
Screenshot 2023-01-03 at 13 34 30

I think this will limit the future of Wrangler as an API, and it might be worth considering marking more things as experimental. I don't have a full set of things that might change, but as some quick examples:
- `dev()` currently takes a path from which it will read the config. If this is going to be flexible for multiple use cases, `dev()` probably shouldn't know about a config file, it should just take a config object (think of a WfP customer building a CLI, for instance, or indeed Wrangler supporting both TOML and JSON). 
- Similarly for auth handling—AFAIK `dev()` currently handles Oauth—but this should probably be handled at the wrapping CLI layer (i.e. in Wrangler proper), and `dev()` should take API keys.

I don't know if these need to block `unstable_dev` -> `dev`, but I do think they need more thinking about, and so to allow for that in the future, `dev()` should mark more of it's options as experimental (I would would lean towards all of them, to be honest, except maybe `port`)

cc @mrbbot

**Comment by rozenmd** [comment]
> I would would lean towards all of them, to be honest, except maybe port

@penalosa At that point, what's the difference between an experimental object containing the entire API, and not promoting unstable_dev to dev? We have to commit to the code we release at some point 😅

**Comment by JacobMGEvans** [comment]
> > I would would lean towards all of them, to be honest, except maybe port
> 
> @penalosa At that point, what's the difference between an experimental object containing the entire API, and not promoting unstable_dev to dev? We have to commit to the code we release at some point 😅

I agree with Max here, since the API is directly utilizing the implementations of the CLI side and they are not "experimental" it doesn't make much since they would be "experimental" here. The API should reflect the current CLI implementation, eventually things will change, however we had talked about the CLI being implemented with the API which would be major/breaking changes to API would be to the CLI as well. 

I also think making everything "experimental" in API options shows a lack of confidence in current implementations that those options represent in CLI as they are now.

**Comment by rozenmd** [comment]
Cool, fair enough - are there plans to write an issue to explain https://github.com/cloudflare/workers-sdk/pull/4175? Feels a bit opaque from the outside.

**Comment by lrapoport-cf** [comment]
hey @rozenmd, apologies for the delay! we've created a [milestone for the wrangler as a library work](https://github.com/cloudflare/workers-sdk/milestone/11) that includes a summary issue for the work (https://github.com/cloudflare/workers-sdk/issues/4730). we'll be tracking related PRs against that issue and within the milestone moving forward :)

**Pull request closed without merging**
