### PR TITLE
wrangler: Add AI binding

### PR DESCRIPTION
**Pull request by edevil**
Added binding for the AI project.

**Author has included the following, where applicable:**

- [x] Tests
- [x] Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))

**Reviewer is to perform the following, as applicable:**

- Checked for inclusion of relevant tests
- Checked for inclusion of a relevant changeset
- Checked for creation of associated docs updates
- Manually pulled down the changes and spot-tested

### CODE REVIEW

**Review by penalosa — COMMENTED** [review]
This is looking good! It would be great to see some more tests in `packages/wrangler/e2e/deploy.test.ts` (similar to the queues tests in that file) to verify that the binding is being passed through and uploaded properly

**Comment by edevil** [comment]
Added missing test @penalosa .

**Review by JacobMGEvans — APPROVED** [review]
This is looking great! The additional tests are super helpful as well, thank you 😄

**Review by penalosa — APPROVED** [review]

**Comment by penalosa** [comment]
LGTM! It would be nice to see an example Wrangler TOML file and some more explanation of how to use this in the changeset file, but non-blocking given the timeline

**Comment by edevil** [comment]
Added examples to changeset.

**Comment by edevil** [comment]
Can this be merged? I don't have write permissions to this repo. Thanks.

**Pull request merged**
