### PR TITLE
fix(startApiDev): pass `accountId` to `startDevServer`

### PR DESCRIPTION
**Pull request by SimonDegraeve**
I realized that `unstable_dev()` accepted an `accountId` argument, but the value was not passed down to the dev server, leading to error with remote KV.
See [here](https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/src/dev/local.tsx#L823), the `accountId` being undefined lead to `cloudflareFetch` being undefined.

### CODE REVIEW

**Comment by JacobMGEvans** [comment]
Looks like the new `args` expression there doesn't have the `accountId` on the types and is failing in the builds.

**Comment by SimonDegraeve** [comment]
@JacobMGEvans I updated the code.

**Comment by SimonDegraeve** [comment]
@mrbbot could you have another look at this PR ? Thank you

**Comment by 1000hz** [comment]
@SimonDegraeve the build is currently failing with the following error
```
Error: R] Cannot use "||" with "??" without parentheses
  
      src/dev.tsx:453:57:
        453 │ ...accountId ?? configParam.account_id || getAccountFromCache()?.id}
            ╵                                        ~~
  
    Expressions of the form "x ?? y || z" are not allowed in JavaScript. You must disambiguate between "(x ?? y) || z" and "x ?? (y || z)" by adding parentheses.
  
  Error: Build failed with 1 error:
  src/dev.tsx:453:57: ERROR: Cannot use "||" with "??" without parentheses
      at failureErrorWithLog (/home/runner/work/workers-sdk/workers-sdk/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:16[36](https://github.com/cloudflare/workers-sdk/actions/runs/6174234974/job/16836272403?pr=3109#step:8:37):15)
      at /home/runner/work/workers-sdk/workers-sdk/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:1048:25
      at /home/runner/work/workers-sdk/workers-sdk/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:993:52
      at buildResponseToResult (/home/runner/work/workers-sdk/workers-sdk/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:10[46](https://github.com/cloudflare/workers-sdk/actions/runs/6174234974/job/16836272403?pr=3109#step:8:47):7)
      at /home/runner/work/workers-sdk/workers-sdk/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:1075:16
      at responseCallbacks.<computed> (/home/runner/work/workers-sdk/workers-sdk/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:697:9)
      at handleIncomingPacket (/home/runner/work/workers-sdk/workers-sdk/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:752:9)
      at Socket.readFromStdout (/home/runner/work/workers-sdk/workers-sdk/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:673:7)
      at Socket.emit (node:events:526:28)
      at addChunk (node:internal/streams/readable:315:12) {
    errors: [
      {
        detail: undefined,
        id: '',
        location: [Object],
        notes: [Array],
        pluginName: '',
        text: 'Cannot use "||" with "??" without parentheses'
      }
    ],
    warnings: []
  }
   ELIFECYCLE  Command failed with exit code 1.
   ELIFECYCLE  Command failed with exit code 1.
   ```

**Pull request merged**
