### PR TITLE
[wrangler]: Remove txt/html loaders when bundling Functions

### PR DESCRIPTION
**Pull request by CarmenPopoviciu**
Up until now, Pages handled `.txt` and `.html` file imports in Functions
via esbuild's [loader](https://esbuild.github.io/api/#loader) option. With
the landing of the Wasm module support in Pages Functions, `.txt` and `.html`
file imports are now handled as external modules imports, and the existing
esbuild `loader` configuration we have in place for such file types, is
completely ignored.

This commit cleans up the no longer used esbuild txt and html loaders, from
both Functions and _worker.js bundling configurations. It also adds relevant
tests and fixtures for these specific file type imports, that should have
been part of our Wasm support PR, but unfortunately weren't.

Fixes # [insert GH or internal issue number(s)].

**What this PR solves / how to test:**

**Associated docs issue(s)/PR(s):**

- [insert associated docs issue(s)/PR(s)]

**Author has included the following, where applicable:**

- [x] Tests
- [ ] Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))

**Reviewer has performed the following, where applicable:**

- [ ] Checked for inclusion of relevant tests
- [ ] Checked for inclusion of a relevant changeset
- [ ] Checked for creation of associated docs updates
- [ ] Manually pulled down the changes and spot-tested

### CODE REVIEW

**Review by WalshyDev — APPROVED** [review]

**Comment by petebacondarwin** [comment]
Can you add a changeset for this please, @CarmenPopoviciu?
Also, when thinking about what will go in the changeset, I would say that `remove txt/html loaders...` is the implementation but not the outward facing change, which is to upload HTML and TXT files as external modules, rather than bundling them into the source code. Right?

**Comment by CarmenPopoviciu** [comment]
@petebacondarwin importing txt and html modules as external modules landed when we released our wasm support work. IMO this PR does some cleanup and test work that should have been done when we worked on our wasm support PR. This is how I thought abt it and why I left out the changeset. But if we think we need one, happy to add it!

**Comment by CarmenPopoviciu** [comment]
> "So this is the step that actually turns that feature on"
My mistake, I should have been more clear abt this. The feature is already available for the users, and those loaders are currently simply ignored. For example, here is the output `_worker.bundle` when you `wrangler pages functions build` a Pages function that imports a text module:

```
------formdata-undici-040367730558
import hello from "./7b502c3a1f48c8609ae212cdfb639dee39673f5e-hey.txt";
async function onRequest() {
  return new Response(hello);
}
------formdata-undici-040367730558
Content-Disposition: form-data; name="./7b502c3a1f48c8609ae212cdfb639dee39673f5e-hey.txt"; filename="./7b502c3a1f48c8609ae212cdfb639dee39673f5e-hey.txt"
Content-Type: text/plain

Hello world
------formdata-undici-040367730558--
```

So this PR doesn't change anything from a user's perspective.

**Comment by petebacondarwin** [comment]
Ah I was thrown by the addition of tests. Are you saying that those tests pass without the change to the loaders?
If so, then indeed this is just an internal refactor, and no release will be needed for the user to access the feature, and so no changeset is needed. (Although in that case a very clear commit would be helpful)

**Comment by CarmenPopoviciu** [comment]
> Are you saying that those tests pass without the change to the loaders?

Yes, that's correct. I've updated the commit message to hopefully smth more descriptive and less confusing

**Comment by jahands** [comment]
Please add a changeset file:
```shell
npx changeset
```

**Pull request merged**
