### PR TITLE
chore: update Remix fixture

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Bringing it in line with latest template

---

Resubmission of #3871

CC/ @RamIdeas @lrapoport-cf

### CODE REVIEW

**Comment by RamIdeas** [comment]
Thanks for taking the time to make this contribution. When you say you're bringing it inline with the latest template, do you mean the latest template C3 would create?

I see no problem getting these changes in except the package.json scripts need to retain the script "test:ci" so that the tests actually run in CI

I've resolved the conflicts and added the "test:ci" script back. When the checks all pass, I will merge 👍

**Review by RamIdeas — APPROVED** [review]

**Comment by RamIdeas** [comment]
Seems there are some TypeScript issues in the React code

image

**Comment by petebacondarwin** [comment]
@MichaelDeBoey - do you still want to land this PR?
If so, can you rebase and respond to @RamIdeas's questions above?
Thanks!

**Comment by MichaelDeBoey** [comment]
> Thanks for taking the time to make this contribution. When you say you're bringing it inline with the latest template, do you mean the latest template C3 would create?

@RamIdeas No, I'm talking about latest Remix template

> @MichaelDeBoey - do you still want to land this PR? If so, can you rebase

@petebacondarwin I've rebased and fixed conflicts

**Comment by andyjessop** [comment]
@MichaelDeBoey it seems there are no blockers to getting this merged other than the test/lint suites passing.

**Comment by petebacondarwin** [comment]
I have rebased this one more time but it is now breaking a whole load of stuff.

Given that we have Remix framework option in C3, which is even tested in our e2e tests, I feel that there is not so much value in having this as a fixture any more, and that we actually just remove this fixture altogether...

**Comment by petebacondarwin** [comment]
https://github.com/cloudflare/workers-sdk/pull/6166

**Pull request closed without merging**
