### PR TITLE
[Templates] Update Rust

### PR DESCRIPTION
**Pull request by nouzu**
**What this PR solves / how to test:**
1. The current template contains a lot of unnecessary code. It is annoying to remove it every time.
2. The Rust edition is set to 2018.
3. `README.md` is lying about non-existent npm `build` script.
4. None of the npm scripts work because of a bug in wasm-pack.

### CODE REVIEW

**Review by JacobMGEvans — CHANGES_REQUESTED** [review]
Looking great for a simplified and improved Rust template! 

Just need the CI check issue to be resolved and the spacing at the end of the file.

**Review by JacobMGEvans — APPROVED** [review]
Great thanks for the PR improving the Templates!

**Comment by Alex1607** [comment]
Even though it might be a bit too late: I wanted to add that I think that the template is worse now.
It leaves new starts in the dark since they will have a harder time finding out how to work with it. I re added the code to the documentation to have a decent starting point for anyone who just started working with rust workers. See PR #3026
cc: @JacobMGEvans

**Comment by JacobMGEvans** [comment]
> Even though it might be a bit too late: I wanted to add that I think that the template is worse now.
> It leaves new starts in the dark since they will have a harder time finding out how to work with it. I re added the code to the documentation to have a decent starting point for anyone who just started working with rust workers. See PR #3026
> cc: @JacobMGEvans 

I appreciate the feedback. I can understand where you are coming from as well, however, the template is meant as a bare minimum starting point for experimental support of Rust. 

I am more than happy to have the parts that were removed added to the docs for now and we can revisit the approach to the experimental templates.

**Comment by Alex1607** [comment]
> > Even though it might be a bit too late: I wanted to add that I think that the template is worse now.
> > It leaves new starts in the dark since they will have a harder time finding out how to work with it. I re added the code to the documentation to have a decent starting point for anyone who just started working with rust workers. See PR #3026
> > cc: @JacobMGEvans
> 
> I disagree. Templates exist to avoid writing boilerplate, not to teach people how to use the library.

Fair enough, I can get behind this. Nevertheless, I think the addition of an example anyone can get started with in the documentation would be a good thing.

**Comment by nouzu** [comment]
> > > Even though it might be a bit too late: I wanted to add that I think that the template is worse now.
> > > It leaves new starts in the dark since they will have a harder time finding out how to work with it. I re added the code to the documentation to have a decent starting point for anyone who just started working with rust workers. See PR #3026
> > > cc: @JacobMGEvans
> > 
> > 
> > I disagree. Templates exist to avoid writing boilerplate, not to teach people how to use the library.
> 
> Fair enough, I can get behind this. Nevertheless, I think the addition of an example anyone can get started with in the documentation would be a good thing.

I don't mind a comment and maybe a few lines of code in main.rs to guide people in the right direction, but very often it just gets out of hand. A good example is Qwik's template, they've got a full-blown app in there.

**Comment by JacobMGEvans** [comment]
> > > > Even though it might be a bit too late: I wanted to add that I think that the template is worse now.
> > > > It leaves new starts in the dark since they will have a harder time finding out how to work with it. I re-added the code to the documentation to have a decent starting point for anyone who just started working with rust workers. See PR #3026
> > > > cc: @JacobMGEvans
> > > 
> > > 
> > > I disagree. Templates exist to avoid writing boilerplate, not to teach people how to use the library.
> > 
> > Fair enough, I can get behind this. Nevertheless, I think the addition of an example anyone can get started within the documentation would be a good thing.
> 
> I don't mind a comment and maybe a few lines of code in main.rs to guide people in the right direction, but very often it just gets out of hand. A good example is Qwik's template, they've got a full-blown app in there.

I'm alright with the docs section having some implementation examples and advanced usage. I will take a look at the #3026 when I get a chance. 

I appreciate the passionate discussion 😁

**Pull request merged**
