### PR TITLE
Update upstream devtools commit

### PR DESCRIPTION
**Pull request by irvinebroque**
refs EW-8447

Haven't updated since 2023. See if this works on preview build

### CODE REVIEW

**Comment by threepointone** [comment]
Wanna land this?

**Comment by petebacondarwin** [comment]
@penalosa is the knowledge leader here. Let's wait for him to take a look on Monday.

**Comment by irvinebroque** [comment]
We need EW-8447 to be addressed first — get inspector bits working first, then test it out with this change. See internal.

**Review by penalosa — CHANGES_REQUESTED** [review]
This also requires changes to the devtools patches to unhide the perfomance tab (pending internal work)

**Comment by penalosa** [comment]
This is being addressed in https://github.com/cloudflare/workers-sdk/pull/7137

**Pull request closed without merging**
