### PR TITLE
fix: custom build noop causes esbuild to skip bundling

### PR DESCRIPTION
**Pull request by RamIdeas**
now, if esbuild doesn't start bundling within a timeout of the custom build finishing, we assume it has decided to skip bundling and continue with the previous bundle output

This is alternative fix from #5741 but the guarantee of requests using your latest code changes is maintained

## What this PR solves / how to test

Fixes #[insert GH or internal issue number(s)].

## Author has addressed the following

- Tests
  - [ ] TODO (before merge)
  - [x] Included
  - [ ] Not necessary because:
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [ ] TODO (before merge)
  - [ ] Included
  - [ ] Not necessary because:
- Public documentation
  - [ ] TODO (before merge)
  - [ ] Cloudflare docs PR(s): <https://github.com/cloudflare/cloudflare-docs/pull/>...
  - [ ] Not necessary because:

### CODE REVIEW

**Comment by RamIdeas** [comment]
@Cherry can you confirm this resolves #5729 please?

**Comment by Cherry** [comment]
This doesn't appear to resolve the issue unfortunately, no. If I open a file and just re-save it without any changes a few times, requests hang again.

**Comment by RamIdeas** [comment]
Ah ok I tried it myself and the problem isn't just that esbuild isn't rebundling, it's that miniflare therefore isn't reloading either.

I have updated this PR and verified that it fixes your reproduction. If you have time to verify it, please let us know, thanks.

**Comment by Cherry** [comment]
This does appear to resolve it now, yes, thank you!

I did get the following error once or twice when I spammed saving:
```
✘ [ERROR] No matching export in "dist/index.mjs" for import "default"
[wrangler]
[wrangler]     .wrangler/tmp/bundle-JUf0Z6/middleware-insertion-facade.js:1:11:
[wrangler]       1 │         import worker, * as OTHER_EXPORTS from "E:\\GitHub\\xxx...
[wrangler]         ╵                ~~~~~~
```

It didn't appear to impact anything though.

**Comment by RamIdeas** [comment]
Thanks for confirming!

My guess is that error is because, while you spammed save, the imported file was still being written to.

**Comment by RamIdeas** [comment]
I've added an e2e regression test for this bug but the test passes with AND without the fix too – not entirely sure why since I can reliably reproduce the bug manually and this PR reliably fixes the bug.

This codepath will be rewritten in the next couple weeks (to avoid useEffect dependency nightmares like this) amongst other planned work. I am happy to merge this as-is.

**Review by petebacondarwin — APPROVED** [review]

**Pull request merged**
