### PR TITLE
pages: remove beta warning

### PR DESCRIPTION
**Pull request by elithrar**
- Removes the Pages beta warning from all Pages commands
- Cleans up imports
- Removes the exported pagesBetaWarning const

### CODE REVIEW

**Comment by elithrar** [comment]
CI fails:

```sh
> create-cloudflare@2.0.9 check:type
ERROR: "check:format" exited with 1.
> tsc --noEmit
```

Running `npm run check:type` directly shows a ton of unrelated errors to any changes in this PR.

**Comment by elithrar** [comment]
```sh
➜  npm run check:format

> wrangler-root@0.0.0 check:format
> prettier . --check --ignore-unknown

Checking formatting...
All matched files use Prettier code style!
```
```sh
> eslint "packages/**/*.[tj]s?(x)" --cache --cache-strategy content --max-warnings=0 --config ./.eslintrc.js --fix


Oops! Something went wrong! :(

ESLint: 8.42.0

ESLint couldn't find the plugin "@typescript-eslint/eslint-plugin".

(The package "@typescript-eslint/eslint-plugin" was not found when loaded as a Node module from the directory "/Users/matt/repos/workers-sdk".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install @typescript-eslint/eslint-plugin@latest --save-dev

The plugin "@typescript-eslint/eslint-plugin" was referenced from the config file in "--config#overrides[0]".
```

`npm i` fails to correctly install `eslint` and related deps due to node-gyp (native binding) issues.

**Comment by elithrar** [comment]
@JacobMGEvans - if you can commit a fix to this PR to address what CI is failing on (since it doesn't expose it to me) it'd be appreciated.

**Comment by rozenmd** [comment]
@elithrar fixed

**Review by GregBrimble — CHANGES_REQUESTED** [review]
Have you spoken to the Pages team about this yet? We'll very likely be making changes here in v4 with convergence, so I'm hesitant to remove the beta label just for the sake of it.

**Review by GregBrimble — APPROVED** [review]
Discussed internally — happy to approve now :) ✅

**Pull request merged**
