### PR TITLE
chore: fix entrypoint logic and refactor

### PR DESCRIPTION
**Pull request by andyjessop**
## What this PR solves / how to test

Fixes #000. This was supposed to fix (but doesn't) #6353. However, it does do a refactor that improves the code base and adds a relevant test case.

## Author has addressed the following

- Tests
  - [ ] TODO (before merge)
  - [x] Tests included
  - [ ] Tests not necessary because:
- E2E Tests CI Job required? (Use "e2e" label or ask maintainer to run separately)
  - [ ] I don't know
  - [x] Required
  - [ ] Not required because:
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [ ] TODO (before merge)
  - [ ] Changeset included
  - [x] Changeset not necessary because: Small refactor
- Public documentation
  - [ ] TODO (before merge)
  - [ ] Cloudflare docs PR(s): 
  - [x] Documentation not necessary because: Bug fix

### CODE REVIEW

**Comment by penalosa** [comment]
I'm pretty sure the fix for the original issue is to change https://github.com/cloudflare/workers-sdk/tree/main/packages/wrangler/src/dev/miniflare.ts#L291-L292 to `const modulesRoot = config.bundle.entry.moduleRoot;`

**Review by penalosa — APPROVED** [review]

**Comment by andyjessop** [comment]
> I'm pretty sure the fix for the original issue is to change https://github.com/cloudflare/workers-sdk/tree/main/packages/wrangler/src/dev/miniflare.ts#L291-L292 to `const modulesRoot = config.bundle.entry.moduleRoot;`

Or better yet, make miniflare respect the config setting? We have `build.moduleRoot` in the config object, we just don't pass it through when generating the miniflare config.

**Comment by penalosa** [comment]
> Or better yet, make miniflare respect the config setting? 

I'm not sure I get the distinction here—`config.bundle.entry` _is_ the config setting. It comes from https://github.com/cloudflare/workers-sdk/tree/main/packages/wrangler/src/dev/use-esbuild.ts#L233. Once we get rid of the non --x-dev-env flow we can probably pass it through to miniflare.ts from the LocalRuntimeController more cleanly

**Comment by andyjessop** [comment]
@penalosa ah, got it. Thanks for pointing that out 👍 

Config is a bit messy and could do with some consolidation I think.

**Comment by andyjessop** [comment]
> I'm pretty sure the fix for the original issue is to change https://github.com/cloudflare/workers-sdk/tree/main/packages/wrangler/src/dev/miniflare.ts#L291-L292 to `const modulesRoot = config.bundle.entry.moduleRoot;`

@penalosa, I think this change is causing the E2E tests to fail. From what I can tell, the `config.bundle.entry.moduleRoot` is referring to the worker definition, but the `scriptPath` was referring to the bundled code (located at `.wrangler/tmp/dev-[hash]/index.js`.

**Pull request merged**
