### PR TITLE
Change init to default to `cloudflare@latest` instead of `cloudflare@2`

### LINKED ISSUE #3900: 🐛 BUG: wrangler init tells you to use cloudflare@2 (instead of cloudflare@latest)
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

Wrangler 3.7.0

### What version of Node are you using?

_No response_

### What operating system are you using?

Mac

### Describe the Bug

mockassignment git:(main) ✗ wrangler init
 ⛅️ wrangler 3.7.0
------------------
Using npm as package manager.
▲ [WARNING] The `init` command is no longer supported. Please use `npm create cloudflare@2` instead.

  The `init` command will be removed in a future version.

Running `npm create cloudflare@2`...

### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by jspspike**
Fixes #3900

Not sure if we're worried about possibly doing a major version bump of create cloudflare that would break wrangler users?

**Associated docs issue(s)/PR(s):**

- [insert associated docs issue(s)/PR(s)]

**Author has included the following, where applicable:**

- [ ] Tests
- [ ] Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))

**Reviewer is to perform the following, as applicable:**

- Checked for inclusion of relevant tests
- Checked for inclusion of a relevant changeset
- Checked for creation of associated docs updates
- Manually pulled down the changes and spot-tested

**Note for PR author:**

We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take inspiration and learn from it.

### CODE REVIEW

**Comment by penalosa** [comment]
I think the initial intention here was to pin `cloudflare@2` instead of `cloudflare@latest` to ensure that breaking changes in the C3 CLI wouldn't affect older Wrangler users. I still think that's a good idea, and I'm not sure we should be using `@latest` like this here. Is there a specific concern with using `@2`?

**Comment by RamIdeas** [comment]
I think we should add a `latest-2` tag to our CI and change the wrangler init to default to `create-cloudflare@latest-2`

**Comment by petebacondarwin** [comment]
Didn't we agree that we would keep Wrangler and C3 in sync from a major version point of view, no?

**Comment by lrapoport-cf** [comment]
hey @penalosa @RamIdeas @petebacondarwin :) did we come to a consensus on whether to move forward with this or not?

**Comment by RamIdeas** [comment]
@lrapoport-cf we spoke about this across a few meetings. We did agree to keep wrangler and C3 in sync from a major version point of view, like @petebacondarwin said. This PR will need to change to use `create-cloudflare@v2-latest` not `create-cloudflare@latest` or `create-cloudflare@2` once the tag is being created/updated (when this PR is merged https://github.com/cloudflare/workers-sdk/pull/3952)

For context, drawbacks of:
- wrangler using `create-cloudflare@latest`: when a new major version of C3 is released which is incompatible with wranglers current usage, old installations of wrangler will begin fail on `wrangler init`.
- wrangler using `create-cloudflare@2`: npm seems to special case numbered tags and resolve to whatever v2 you have cached even if there is a newer (minor/patch) version of v2

If wrangler uses `create-cloudflare@v2-latest`, it would be the best of both worlds: older cached versions of v2 are ignored if a newer v2 exists. If the newest v2 is already cached, it is used.

**Comment by jculvey** [comment]
I think things change might not be needed.

C3 will automatically update to the latest minor version if it's available. Assuming we synchronize our major version, it will effectively accomplish the intent of this PR.

This functionality was supposed to already be in place, but we recently discovered that there was a regression that removed it in `create-cloudflare@2.2.1`. There's an [open PR to fix this](https://github.com/cloudflare/workers-sdk/pull/4136) which should hopefully be released soon.

**Comment by jspspike** [comment]
Clsoing this PR based on @jculvey's comment

**Pull request closed without merging**
