### PR TITLE
make the workerd compatibility date retrieval more stable by fetching it directly from the npm registry

### PR DESCRIPTION
**Pull request by dario-piotrowicz**
It seems like the workerd compatibility retrieval can have some issues with different package managers (or at least with `yarn`):
- https://github.com/cloudflare/workers-sdk/actions/runs/7211842007/job/19748508606?pr=4602#step:4:65
- https://github.com/cloudflare/workers-sdk/actions/runs/7250601828/job/19751164094?pr=4604#step:4:65
- https://github.com/cloudflare/workers-sdk/actions/runs/7246672804/job/19747293009?pr=4617#step:4:65
- https://github.com/cloudflare/workers-sdk/actions/runs/7246765792/job/19742158656?pr=4618#step:4:65
- https://github.com/cloudflare/workers-sdk/actions/runs/7260941093/job/19781139701?pr=4629#step:4:65

The changes here make this more stable by always using fetching the date directly from the npm registry instead

### CODE REVIEW

**Review by jculvey — APPROVED** [review]

**Review by petebacondarwin — APPROVED** [review]

**Comment by Skye-31** [comment]
Arguably, you could make it more stable by fetching from the NPM registry directly, instead of assuming the user has NPM installed (looking at bun users here)

**Comment by petebacondarwin** [comment]
> Arguably, you could make it more stable by fetching from the NPM registry directly (`https://registry.npmjs.org/workerd` -> `dist-tags` -> `latest`), instead of assuming the user has NPM installed (looking at bun users here)

Good call for bun users... 🤔 

Also, does this need to work offline?

**Comment by dario-piotrowicz** [comment]
> Also, does this need to work offline?

I don't think C3 needs to work offline, does it? 🤔 
In any case if the date fetch fails then it falls back to `2023-05-18`, so I guess that's fine 🙂 
https://github.com/cloudflare/workers-sdk/blob/421cd584a678a97de2f24e1c1b28a766f984148e/packages/create-cloudflare/src/helpers/command.ts#L400

**Comment by dario-piotrowicz** [comment]
> Arguably, you could make it more stable by fetching from the NPM registry directly (`https://registry.npmjs.org/workerd` -> `dist-tags` -> `latest`), instead of assuming the user has NPM installed (looking at bun users here)

ok thanks good point I will update it to be a raw fetch 🙂:+1:
(can bun users really not have npm installed? 😱 🥲)

**Comment by jculvey** [comment]
Still LGTM

**Pull request merged**
