### PR TITLE
chore: change vitest config to be ESM (for sure) to avoid warnings

### PR DESCRIPTION
**Pull request by petebacondarwin**
Without this we often see:

```
 The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
```

### CODE REVIEW

**Comment by threepointone** [comment]
omg yes

**Review by threepointone — APPROVED** [review]

**Review by threepointone — APPROVED** [review]

**Comment by petebacondarwin** [comment]
An alternative solution to changing the file name is to set `"type": "module"` in various `package.json` files but that seemed like a more dangerous change.

**Review by CarmenPopoviciu — APPROVED** [review]

**Comment by andyjessop** [comment]
> An alternative solution to changing the file name is to set `"type": "module"` in various `package.json` files but that seemed like a more dangerous change.

I wonder if it's worth doing just that, as a fail-fast mechanism. If users have `"type": "module"` and it breaks things, we likely want to know about it as soon as possible.

**Comment by petebacondarwin** [comment]
> > An alternative solution to changing the file name is to set `"type": "module"` in various `package.json` files but that seemed like a more dangerous change.
> 
> I wonder if it's worth doing just that, as a fail-fast mechanism. If users have `"type": "module"` and it breaks things, we likely want to know about it as soon as possible.

By dangerous change, I meant that switching the default format for the packages in our repo could have consequences outside of Vitest that I didn't want to start messing with. Not that we potentially don't support such packages.

**Review by andyjessop — APPROVED** [review]

**Review by RamIdeas — APPROVED** [review]

**Pull request merged**
