### PR TITLE
feat(wrangler): able to deploy complex worker to Workers for Platforms

### PR DESCRIPTION
**Pull request by andrasbacsai**
What this PR solves / how to test:
We (https://webstudio.is) would like to deploy complex ([Remix-based](https://remix.run/)) customer applications to Workers for Platforms, which is not possible currently using wrangler and requires a custom script.

Adding an option `platformNamespace` to `wrangler` makes it possible to:
1. Upload all generated static assets to the KV store.
2. Upload the worker to the namespace instead of the normal Workers' namespace.

Associated docs issues/PR:

- [insert associated docs issue(s)/PR(s)]

Author has included the following, where applicable:

- [ ] Tests
- [x] Changeset

Reviewer has performed the following, where applicable:

- [x] Checked for inclusion of relevant tests
- [x] Checked for inclusion of a relevant changeset
- [ ] Checked for creation of associated docs updates
- [ ] Manually pulled down the changes and spot-tested

Fixes # [insert issue number].
No issue opened.

### CODE REVIEW

**Comment by admah** [comment]
@andrasbacsai thank you for submitting this PR. Since this has the potential to expand the scope of Wrangler quite a bit, we will need some time to sync up with the Workers for Platforms team and have them review as well.

**Comment by andrasbacsai** [comment]
> @andrasbacsai thank you for submitting this PR. Since this has the potential to expand the scope of Wrangler quite a bit, we will need some time to sync up with the Workers for Platforms team and have them review as well.

Sure! Thanks for the reply! Just so you know, I've tested it out and it works perfectly. It uploads all the necessary assets to a KV store and publishes the customer worker to the dispatch namespace. 

However, it needs a bit different worker to be able to retrieve the assets; due to that, we are using a SPA (Remix based), and the asset names are different in the index.html than the asset names in the KV store (it has an extra hash in the filenames). We need to use the asset manifest file to reroute all files to the correct KV store key names.

I place here the worker's full code (not that long), so if anyone faces the same issue, this could be helpful.

```
import { getAssetFromKV } from "@cloudflare/kv-asset-handler";
import { createRequestHandler } from "@remix-run/cloudflare";
// Location of the build Remix SPA
import * as build from "../build";
import manifestJSON from "__STATIC_CONTENT_MANIFEST";

const assetManifest = JSON.parse(manifestJSON);
const handleRemixRequest = createRequestHandler(build, process.env.NODE_ENV);
export default {
  async fetch(
    request: Request,
    env: Env,
    ctx: ExecutionContext
  ): Promise<Response> {
    try {
      const url = new URL(request.url);
      const ttl = url.pathname.startsWith("/build/")
        ? 60 * 60 * 24 * 365 // 1 year
        : 60 * 5; // 5 minutes
      const asset = assetManifest[url.pathname.replace(/^\/+/, '')]
      let finalRequest = request

      // If the asset is found in the assetManifest json, we simple request it with the right KV store key name

      if (asset) {
        finalRequest = new Request(url.origin + '/' + asset, {
          ...request
        });
      }
      return await getAssetFromKV(
        {
          request: finalRequest,
          waitUntil(promise) {
            return ctx.waitUntil(promise);
          },
        },
        {
          ASSET_NAMESPACE: env.__STATIC_CONTENT,
          ASSET_MANIFEST: assetManifest,
          cacheControl: {
            browserTTL: ttl,
            edgeTTL: ttl,
          },
        }
      );
    } catch (error) {
    }

    try {
      const loadContext = env;
      return await handleRemixRequest(request, loadContext);
    } catch (error) {
      return new Response("An unexpected error occurred", { status: 500 });
    }
  },
};

```

**Comment by 1000hz** [comment]
Looping in @tanushreesharma-cf since this falls within the scope of her team's work. Could you take a look at what this PR is proposing? Let's discuss how we want to handle this in wrangler.

**Comment by lrapoport-cf** [comment]
hey @tanushreesharma-cf , just bumping this :) could you please take a look so we can discuss the best way to move forward?

**Pull request closed without merging**
