### PR TITLE
fix: infinite loop if spawning command fails in `pages dev`

### LINKED ISSUE #1544: 🐛 BUG: `pages dev` hangs when using proxy command that is not executable
### What version of `Wrangler` are you using?

2.0.23

### What operating system are you using?

Linux

### Describe the Bug

Running `wrangler pages dev -- COMMAND` hangs wrangler if `COMMAND` is not an executable (or doesn't exist, even)
`SIGINT` (`CTRL+C`) does not terminate the process.

Noticed when reporting #1543.

### PR DESCRIPTION
**Pull request by Martin-Eriksson**
Closes #1544.

### CODE REVIEW

**Comment by JacobMGEvans** [comment]
@cloudflare/pages Thoughts on testing this?

**Comment by WalshyDev** [comment]
This will at least fail now:
```
➜  cf-sso git:(main) npx https://prerelease-registry.developers.workers.dev/runs/2736122461/npm-package-wrangler-1546 pages dev -- a       
Need to install the following packages:
  https://prerelease-registry.developers.workers.dev/runs/2736122461/npm-package-wrangler-1546
Ok to proceed? (y) 
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
🚧 'wrangler pages <command>' is a beta command. Please report any issues to https://github.com/cloudflare/wrangler2/issues/new/choose
Running a...
/home/walshy/.npm/_npx/d11ffa3a744dd226/node_modules/wrangler/wrangler-dist/cli.js:12025
            throw ex;
            ^

Error: spawn a ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn a',
  path: 'a',
  spawnargs: []
}
```

Whereas before it hung:
```
  cf-sso git:(main) wrangler pages dev -- a
🚧 'wrangler pages <command>' is a beta command. Please report any issues to https://github.com/cloudflare/wrangler2/issues/new/choose
Running a...
```

So this is an improvement. We should probably have a proper error message for it though

**Review by petebacondarwin — APPROVED** [review]

**Comment by JacobMGEvans** [comment]
Reviving this, @WalshyDev does anyone in Pages want to pick this up?

**Comment by WalshyDev** [comment]
Let me see on Monday if anyone has some free cycles

@Skye-31 may also be interested

**Review by petebacondarwin — APPROVED** [review]

**Pull request closed without merging**
